### ISSUE TITLE
How to obtain dhall.sublime-syntax from dhall.tmLanguage

### ISSUE THREAD

**Issue by kukimik** [ninth-dev/SublimeText#1]
Hello! Sorry for bothering you in what looks like a rather private repo. However, I'd be grateful for some help.

I believe that you obtained the [Dhall/dhall.sublime-syntax](https://github.com/ninth-dev/SublimeText/blob/master/Dhall/dhall.sublime-syntax) file from the `.tmLanguage` file provided by the VSCode plugin https://github.com/dhall-lang/vscode-language-dhall. (That's because your `.sublime-syntax` file has the same bug, see https://github.com/dhall-lang/vscode-language-dhall/pull/11). Did you do it in an automated way? I tried the approach described in the README, but "Plugin Development: Convert Syntax to .sublime-syntax" fails with the following error (in Sublime Text build 4143):

```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 1659, in run_
    return self.run()
  File "/opt/sublime_text/Packages/Default.sublime-package/convert_syntax.py", line 433, in run
  File "/opt/sublime_text/Packages/Default.sublime-package/convert_syntax.py", line 358, in convert
  File "/opt/sublime_text/Packages/Default.sublime-package/convert_syntax.py", line 328, in make_context
Exception: unknown pattern type: dict_keys(['name', 'patterns'])
```

I'm interested in creating a package for Sublime Text with Dhall syntax highlighting. I want to base it on https://github.com/dhall-lang/vscode-language-dhall,  but it would be nice to have a `.sublime-syntax` file along with the `.tmLanguage` file (although the `.tmLanguage` file itself seems to work and probably is sufficient), and it would be nice if it could be obtained in an automated way.

Disclaimer: there is a [$200 bounty](https://twitter.com/dhall_lang/status/1432025254604390402) set for restoring Dhall syntax highlighting in Sublime after https://github.com/SQbQxeKd3JHD8/SublimeDhall disappeared. If you are interested, go ahead and grab it! I'm interested more in restoring the syntax highlighting than in the bounty.

**Comment by ninth-dev** [comment]
hi @kukimik , it actually wasn't generated from the `.tmLanguage`, it might have been from the repo you linked:  https://github.com/SQbQxeKd3JHD8/SublimeDhall when it was still around.

**Comment by kukimik** [comment]
Ah, thanks a lot. I thought it was generated from the `.tmLanguage` file because I have another `.sublime-syntax` file that was copied from https://github.com/SQbQxeKd3JHD8/SublimeDhall, which looks vastly different. However, I have no information about the chronology/versions/etc., so for example large refactoring work could have happened between the two versions. Thanks again for your reply!
